version: '2'
services:
    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./.basic-auth-password:/etc/prometheus/.basic-auth-password
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - "9090:9090"
    grafana:
        image: grafana/grafana
        volumes:
            - ./grafana-storage:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=pass
        depends_on:
            - prometheus
        ports:
            - "3000:3000"
