"""Hello DB

Revision ID: 6fba9ebf102d
Revises: 
Create Date: 2020-05-04 20:48:47.638083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6fba9ebf102d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('highest_protocol', sa.String(), nullable=True),
    sa.Column('services', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ip_pool',
    sa.Column('ip', sa.String(length=39), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inserted', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('node_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('ip', 'port')
    )
    op.create_table('node_activity',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('start_of_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_of_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_activity')
    op.drop_table('ip_pool')
    op.drop_table('node')
    # ### end Alembic commands ###
